### ISSUE TITLE
Error in index.js when using 'build-css'.

### ISSUE THREAD

**Issue by andrewkojo** [scotch-io/gulp-and-less-starter-kit#3]
Nice intro.. I just cloned your git repository. I added some less code to style.less and as soon as I saved I got:

[14:18:13] Starting 'build-css'...

/html5-boilerplate_v5/gulp-and-less-starter-kit/node_modules/gulp-less/index.js:68

}).done(undefined, cb);

^

TypeError: undefined is not a function

at DestroyableTransform._transform (/html5-boilerplate_v5/gulp-and-less-starter-kit/node_modules/gulp-less/index.js:68:8)

at DestroyableTransform.Transform._read (/html5-boilerplate_v5/gulp-and-less-starter-kit/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)

at DestroyableTransform.Transform._write (/html5-boilerplate_v5/gulp-and-less-starter-kit/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)

at doWrite (/html5-boilerplate_v5/gulp-and-less-starter-kit/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)

at writeOrBuffer (/html5-boilerplate_v5/gulp-and-less-starter-kit/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)

at DestroyableTransform.Writable.write (/html5-boilerplate_v5/gulp-and-less-starter-kit/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)

at write (/html5-boilerplate_v5/gulp-and-less-starter-kit/node_modules/gulp-plumber/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)

at flow (/html5-boilerplate_v5/gulp-and-less-starter-kit/node_modules/gulp-plumber/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)

at DestroyableTransform.pipeOnReadable (/html5-boilerplate_v5/gulp-and-less-starter-kit/node_modules/gulp-plumber/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)

at DestroyableTransform.emit (events.js:129:20)

**Comment by whatnickcodes** [comment]
Update Less to 3.0.0. This is a bug with them and a new version of Node.

So manually go into package.json and change the verson for gulp-less to 3.0.0 or I think you can run

npm update --save-dev

**Comment by andrewkojo** [comment]
gulp-less v3.0.0 failed however using npm update --save-dev got me to 3.0.3 and everything is working fine. Thanks
